In [60]:
import numpy as np

class Node:
    def __init__(self, data=None, next=None):
        self.element = data
        self.next = next

class MyList:
    #Creating Constractor
    def __init__(self,arr=None):
        if arr is None:
            self.head = None
        else:
            self.head = Node(arr[0],None)
            temp = self.head
            for i in range(1,len(arr)):
                temp.next = Node(arr[i],None)
                temp = temp.next

    def ShowList(self):
        n = self.head
        while(n != None):
            print(n.element,end=" ")
            n = n.next
    def rightShift(self):
      pass


a = [1,2,3,4]
arr = np.array(a)
# print(type(arr))
linkList = MyList(arr)
mylist2 = MyList()

linkList.ShowList()
# print(a)
# print(np.zeros((5,), dtype=int))

1 2 3 4 

In [32]:
import numpy as np

arr = np.zeros((3,4),dtype=int)
arr[1,1] = 7
# print(arr)

# lst = 
# arr = [[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[0,0,0]]]
print(arr)
# # Atoshe = arr[0]
# # print(Atoshe)



# print([3,5,6][2])

[list([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) list([[0, 0, 0]])]


<ipython-input-32-9d4e43967618>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[0,0,0]]])


In [35]:
# nested_list = 
arr = np.array([[[1, 2], [5, 6], [9, 10]],
               [[13, 14], [17, 18], [21, 22]]])
print(arr)

[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[13 14]
  [17 18]
  [21 22]]]


In [59]:
arr = np.zeros((5,4),dtype=int)
print(arr)
row, col = arr.shape
count = 1
print('Starting For loop')
for i in range(col):
  for j in range(row):
    # print(arr[i][j])
    if j%2 == 0 and i%2 == 0:
      arr[j][i] = count
      count +=1
print(arr)
t = arr[0].copy()

arr[0] = arr[1]
arr[1] = t
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Starting For loop
[[1 0 4 0]
 [0 0 0 0]
 [2 0 5 0]
 [0 0 0 0]
 [3 0 6 0]]
[[0 0 0 0]
 [1 0 4 0]
 [2 0 5 0]
 [0 0 0 0]
 [3 0 6 0]]


In [65]:
arr = [10,20,30,50,40]




20
36
