**Instructions to Follow (Failing to follow these will result mark penalties).**


1.   You can not use any built-in function except len()
2.   You can not use any other python collections except array (e.g: tuptle, dictionaries etc.). 
3. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be two approach.

  i. arr = np.array([None] * 10) #Initializing an array length 10 with values None.

  ii. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
4. From File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.






In [1]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [2]:
# Complete the functions defined in this cell


# Test 01: Play Right
def playRight(sequence,beats):
  for i in beats:
    if i==1:
      j = len(sequence)-1
      while j > 0:
        if j == len(sequence)-1:
          temp = sequence[j]
        sequence[j] = sequence[j-1]
        j -= 1
      sequence[0] = sequence
  return sequence

def leftShift_from_k(lst,k):
  for i in range(k,len(lst)-1):
    lst[i] = lst[i+1]
    lst[i+1] = 0
# Test 02: Discard Cards
def discardCards(cards,number):
  i = 0
  while i<len(cards):
    if cards[i] == number:
      leftShift_from_k(cards,i)
      i = i - 1
    i = i + 1
  return cards


#Test 03: Merge Lineup
def mergeLineup(pokemon_1, pokemon_2):  
  i = 0
  j = len(pokemon_1) -  1
  arr = np.array([0]*len(pokemon_1))
  print(arr)
  while i<len(pokemon_1):
    if pokemon_1[i] == None: pokemon_1[i] = 0
    if pokemon_2[j] == None: pokemon_2[j] = 0
    arr[i] = pokemon_1[i] + pokemon_2[j]

    i = i + 1
    j = j - 1
  return arr


# Test 04: Balance your Salami
def balanceSalami(salami):
  # TO DO
  return None

# Test 05: Protecc Salami
def protectSalami(salami):
  # TO DO
  return None


# Test 05: Odd Even Wave
def waveYourFlag(arr):
  # TO DO
  return None





In [3]:
# This cell is the driver code
# Run this cell after completion of above function.
# You will see the status Accepted after completion if your code is correct.
# If your function is wrong you will see wrong[correction percentage]
# This is called unit testing if you are wondering the checking approach
# No need to write or change any code here. You can only change the inputs

# print("///  Test 01: Play Right  ///")
# sequence=np.array([10,20,30,40,50,60])
# beats = np.array([1,0,0,1,0,1])
# returned_value = playRight(sequence, beats) 
# print(f'Task 1: {returned_value}') # This should print [40, 50, 60, 10, 20, 30]
# unittest.output_test(returned_value, np.array([40, 50, 60, 10, 20, 30]))


print("///  Test 02: Discard Cards  ///")
cards = np.array([1,2,3,2,8,2,2,5,7])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1, 3, 8, 5, 7, None, None, None, None]
unittest.output_test(returned_value, [1, 3, 8, 5, 7, None, None, None, None])


print("///  Test 03: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

pokemon_1 = np.array([4, 5, None, None])
pokemon_2 = np.array([2, None, None, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,5,0,2]
unittest.output_test(returned_value, np.array([4,5,0,2]))


print("///  Test 04: Balance Your Salami  ///")
salami = np.array([1, 1, 1, 2, 1])
returned_value = balanceSalami(salami)
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = [2, 1, 1, 2, 1]
returned_value = np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

salami = [10, 3, 1, 2, 10] 
returned_value =  np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)


print("///  Test 05: Protecc Salami  ///")
salami = np.array([4,5,6,6,4,3,6,4]) 
returned_value = protectSalami(salami) 
print(f'Task 5: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = np.array([3,4,6,3,4,7,4,6,8,6,6])
returned_value = protectSalami(salami) 
print(f'Task 5: {returned_value}') # This should print False
unittest.output_test(returned_value, False)


print("///  Test 06: Odd Even Wave  ///")
arr = np.array([2,12,3,8,1,5])
returned_value = waveYourFlag(arr) 
print(f'Task 6: {returned_value}') # This should print [2,3,12,1,8,5]
unittest.output_test(returned_value, np.array([2,3,12,1,8,5]))

arr = np.array([45,23,78,84,41])
returned_value = waveYourFlag(arr) 
print(f'Task 6: {returned_value}') # This should print [45,78,23,84,41]
unittest.output_test(returned_value, np.array([45,78,23,84,41]))

///  Test 02: Discard Cards  ///
Task 2: [1 3 8 5 7 0 0 0 0]
Not Accepted [Your output: [1 3 8 5 7 0 0 0 0]  |  Expected Output: [1, 3, 8, 5, 7, None, None, None, None]]
///  Test 03: Merge Lineup  ///
[0 0 0 0 0]
Task 3: [12  3 28 -8  5]
Accepted
[0 0 0 0 0]
Task 3: [ 4 17  6 27  2]
Accepted
[0 0 0 0]
Task 3: [4 5 0 2]
Accepted
///  Test 04: Balance Your Salami  ///
Task 4: None
Wrong Answer [Your output: None  |  Expected Output: True]
Task 4: None
Wrong Answer [Your output: None  |  Expected Output: False]
Task 4: None
Wrong Answer [Your output: None  |  Expected Output: True]
///  Test 05: Protecc Salami  ///
Task 5: None
Wrong Answer [Your output: None  |  Expected Output: True]
Task 5: None
Wrong Answer [Your output: None  |  Expected Output: False]
///  Test 06: Odd Even Wave  ///
Task 6: None
Wrong Answer [Your output: None  |  Expected Output: [ 2  3 12  1  8  5]]
Task 6: None
Wrong Answer [Your output: None  |  Expected Output: [45 78 23 84 41]]


In [4]:
def protectSalami(salami):
  counts = np.zeros(np.max(salami) + 1, dtype=int)
  for note in salami:
    counts[note] += 1
  # print(counts)
  c=1
  tmp=0
  for i in range (len(counts)):
    if counts[i]!= 0:
      for j in range (len(counts)):
        if counts[i]==counts[j]:
          c+=1
          counts[j]=0
      counts[i]=0
    if c==2:
      tmp+=1
      c=1
  if tmp>=1:
    print("Nas")
    return True
  else:
    print(" Khan")
    return False        

# # Test the function
# salami = np.array([4, 5, 6, 6, 4, 3, 6, 4])
# print(protectSalami(salami))  # True

# salami = np.array([3, 4, 6, 3, 4, 7, 4, 6, 8, 6, 6])
# print(protectSalami(salami))  # False
print("///  Test 05: Protecc Salami  ///")
salami = np.array([4,5,6,6,4,3,6,4]) 
returned_value = protectSalami(salami) 
print(f'Task 5: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = np.array([3,4,6,3,4,7,4,6,8,6,6])
returned_value = protectSalami(salami) 
print(f'Task 5: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

///  Test 05: Protecc Salami  ///
Nas
Task 5: True
Accepted
 Khan
Task 5: False
Accepted


In [5]:
def waveYourFlag(arr):
  new = np.array([0] * len(arr))
  for i in range(len(arr)):
      new[i] = arr[i]
  # print(new)
  # print(arr)]
  # Temp 1 means odd lagbe
  #temp 0 means even lagbe
  temp = 0
  i = 0
  res = 0
  while (i < len(new)-1):
    res = 0
    if new[i] % 2 == temp and i == 0:
      temp = 1
      if new[i+1] % 2 != temp:
        for j in range(i+2,len(new)):
          if new[j] % 2 == temp:
            res = j
            break
        tmp = new[i+1]
        new[i+1] = new[res]
        new[res] = tmp
    elif (new[i-1]%2 == new[i]%2 and i != 0):
      res = 0
      for j in range(i+1,len(new)):
        if new[j] % 2 == temp:
          res = j
          break
      tmp = new[i+1]
      new[i+1] = new[res]
      new[res] = tmp
    else:
      res = 0
      temp = 0
      if new[i+1] % 2 != temp:
        for j in range(i+2,len(new)):
          if new[j] % 2 == temp:
            res = j
            break
        tmp = new[i+1]
        new[i+1] = new[res]
        new[res] = tmp
    i+=1
  return new

print("///  Test 06: Odd Even Wave  ///")
arr = np.array([2,12,3,8,1,5])
returned_value = waveYourFlag(arr) 
print(f'Task 6: {returned_value}') # This should print [2,3,12,1,8,5]
unittest.output_test(returned_value, np.array([2,3,12,1,8,5]))

///  Test 06: Odd Even Wave  ///
Task 6: [ 5  3 12  8  2  1]
Not Accepted [Your output: [ 5  3 12  8  2  1]  |  Expected Output: [ 2  3 12  1  8  5]]


In [6]:
def waveYourFlag(arr):
  temp = arr[0]%2 #0
  print(temp)
  i = 1
  while i < len(arr)-1:
    if arr[i]%2 == temp: #0
      res = None
      for j in range(i+1,len(arr)):
        if arr[j] % 2 != temp:
          res = j
          break
       
      if res != None:
        tmp = arr[i]
        arr[i] = arr[res]
        arr[res] = tmp
    temp = arr[i]%2 #
    print(arr[i],temp)
    i +=1
    # print(arr)
  return arr


print("///  Test 06: Odd Even Wave  ///")
arr = np.array([2,12,3,8,1,5])
returned_value = waveYourFlag(arr) 
print(f'Task 6: {returned_value}') # This should print [2,3,12,1,8,5]
unittest.output_test(returned_value, np.array([2,3,12,1,8,5]))

arr = np.array([45,23,78,84,41])
returned_value = waveYourFlag(arr) 
print(f'Task 6: {returned_value}') # This should print [45,78,23,84,41]
unittest.output_test(returned_value, np.array([45,78,23,84,41]))

///  Test 06: Odd Even Wave  ///
0
3 1
12 0
1 1
8 0
Task 6: [ 2  3 12  1  8  5]
Accepted
1
78 0
23 1
84 0
Task 6: [45 78 23 84 41]
Accepted


In [19]:
def waveYourFlag(arr):
  lnth = len(arr)//2
  even_array = np.zeros(lnth+1, dtype = int)
  odd_array = np.zeros(lnth+1, dtype = int)
  new_array = np.zeros(len(arr), dtype =int)
  even_idx = 0
  odd_idx = 0
  for i in range(len(arr)):
    if arr[i]%2 ==0:
      even_array[even_idx] = arr[i]
      even_idx +=1
    else:
      odd_array[odd_idx] = arr[i]
      odd_idx +=1

  print(even_array)
  print(odd_array)
  nt = 0
  even_idx = 0
  odd_idx = 0
  while nt>=0 and nt<(len(new_array)-1):
    if nt%2==0:
      new_array[nt] = even_array[even_idx]
      even_idx +=1
    else:
      new_array[nt] = odd_array[odd_idx]
      odd_idx +=1
    nt +=1


  return new_array


print("///  Test 06: Odd Even Wave  ///")
arr = np.array([2,12,3,8,1,5])
returned_value = waveYourFlag(arr) 
print(f'Task 6: {returned_value}') # This should print [2,3,12,1,8,5]
unittest.output_test(returned_value, np.array([2,3,12,1,8,5]))

# arr = np.array([45,23,78,84,41])
# returned_value = waveYourFlag(arr) 
# print(f'Task 6: {returned_value}') # This should print [45,78,23,84,41]
# unittest.output_test(returned_value, np.array([45,78,23,84,41]))

///  Test 06: Odd Even Wave  ///
[ 2 12  8  0]
[3 1 5 0]
Task 6: [ 2  3 12  1  8  0]
Not Accepted [Your output: [ 2  3 12  1  8  0]  |  Expected Output: [ 2  3 12  1  8  5]]


In [21]:
# Test 06: Odd Even Wave
import numpy as np

arr = np.array([2,12,3,1,5,8])

odd_arr = np.array([None]*len(arr))
even_arr = np.array([None]*len(arr))
final_arr = np.array([None]*len(arr))

odd_index = 0
even_index = 0

for i in range(len(arr)):
  if arr[i] % 2 != 0:
      odd_arr[odd_index] = arr[i]
      odd_index += 1

  else:
    even_arr[even_index] = arr[i]
    even_index+=1

first = arr[0] % 2 
flag = 0
odd_index = 0
even_index = 0
print(odd_arr, even_arr)

for i in range(len(arr)):
  if i == 0:
    final_arr[i] = arr[i]
    if first == 0:
      even_index += 1
      first = 1
    else:
      odd_index += 1
      first = 0  

  elif first == 0:
    final_arr[i] = even_arr[even_index]
    even_index += 1
    first = 1

  else:
    final_arr[i] = odd_arr[odd_index]
    odd_index += 1
    first = 0


print(final_arr)

[3 1 5 None None None] [2 12 8 None None None]
[2 3 12 1 8 5]


In [38]:
import numpy as np
def array_mean(arr):
  sum=0
  for i in range(len(arr)):
    sum+=arr[i]
  return sum/len(arr)


def SD_result(arr):
  all_sum=0
  mean=array_mean(arr)
  for i in range(len(arr)):
    all_sum+=(arr[i]-mean)**2
  div_r=all_sum/(len(arr))
  sd_r=(div_r)**0.5
  return sd_r

def away(arr):
  mean= array_mean(arr)
  std = SD_result(arr)
  new_arr = []
  #new_arr = [x for x in arr if x > mean + (1.5 * std) or x < mean - (1.5 * std)]
  count=0
  for x in arr:
    if x > mean + (1.5 * std) or x < mean -(1.5 * std):
      count+=1
      new_arr=[0]*count  
  j=0
  # print(count)
  # overflow = 0
  for x in arr:
    if x > mean + (1.5 * std) or x < mean - (1.5 * std):
      # print(mean + (1.5 * std))
      new_arr[j]=x
      j+=1
    if j == count:
        return new_arr
  
print('Qus 1')
arr=[10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4]
arr=np.array(arr)
size=len(arr)
print(array_mean(arr))
print("Qus 2")
arr=[10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4]
size=len(arr)
print(SD_result(arr))
print("Qus 3")
print(away(arr))

Qus 1
10.181818181818182
Qus 2
7.589684168997018
Qus 3
2
[25, -5]
